main: eu.metacloudservice.bootstrap.bukkit.BukkitBootstrap
name: metacloud-api
version: 1.1.3-RELEASE
author: RauchigesEtwas
load: STARTUP

description: This is the api of the cloudsystem
website: https://metacloudservice.eu
