main: eu.metacloudservice.bukkit.BukkitBootstrap
version: 1.1.2-RELEASE
author: RauchigesEtwas
name: metacloud-plugin
depend: ["metacloud-api"]

description: This plugin is managing all the background stuff
website: https://metacloudservice.eu

commands:
  service: